=== bdharris08/cs373-wc/wc2.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<xsd:element name="worldCrises">
    <xsd:complexType>
        <xsd:sequence>
            <xsd:element name="crisis" type="crisisType"  maxOccurs="unbounded"/>
            <xsd:element name="organization" type="organizationType"  maxOccurs="unbounded"/>
            <xsd:element name="person" type="personType"  maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
</xsd:element>
 
<xsd:complexType name = "crisisType">
    <xsd:sequence>
        <xsd:element name="name" type="xsd:normalizedString"/>
        <xsd:element name="info" type="crisisInfoType"/>
        <xsd:element name="ref" type="extLinkType"/>
        <xsd:element name="misc" type="xsd:string"/>
        <xsd:element name="org" type="referenceType" maxOccurs="unbounded"/>
        <xsd:element name="person" type="referenceType" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="id" type="xsd:ID" use="required"/>
</xsd:complexType>
 
<xsd:complexType name="organizationType">
    <xsd:sequence>
        <xsd:element name="name" type="xsd:normalizedString"/>
        <xsd:element name="info" type="orgInfoType"/>
        <xsd:element name="ref" type="extLinkType"/>
        <xsd:element name="misc" type="xsd:string"/>
        <xsd:element name="crisis" type="referenceType" maxOccurs="unbounded"/>
        <xsd:element name="person" type="referenceType" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="id" type="xsd:ID" use="required"/>
</xsd:complexType>

<xsd:complexType name="personType">  
    <xsd:sequence>
        <xsd:element name="name" type="xsd:normalizedString"/>
        <xsd:element name="info" type="personInfoType"/>
        <xsd:element name="ref" type="extLinkType"/>
        <xsd:element name="misc" type="xsd:string"/>
        <xsd:element name="crisis" type="referenceType" maxOccurs="unbounded"/>
        <xsd:element name="org" type="referenceType" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="id" type="xsd:ID" use="required"/>
</xsd:complexType>

<xsd:complexType name="locationType">
    <xsd:sequence>
        <xsd:element name="city" type="xsd:normalizedString"/>
        <xsd:element name="region" type="xsd:normalizedString"/>
        <xsd:element name="country" type="xsd:normalizedString"/>
    </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="dateType">
    <xsd:sequence>
        <xsd:element name="time" type="xsd:string"/>
        <xsd:element name="day" type="xsd:integer"/>
        <xsd:element name="month" type="xsd:integer"/>
        <xsd:element name="year" type="xsd:integer"/>
        <xsd:element name="misc" type="xsd:string"/>
    </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="crisisInfoType">
    <xsd:sequence>
        <xsd:element name="history" type="xsd:string"/>
        <xsd:element name="help" type="xsd:string"/>
        <xsd:element name="resources" type="xsd:string"/>
        <xsd:element name="type" type="xsd:normalizedString"/>
        <xsd:element name="time" type="dateType"/>
        <xsd:element name="loc" type="locationType"/>
        <xsd:element name="impact" type="impactType"/>   
    </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="orgInfoType">
    <xsd:sequence>
        <xsd:element name="type" type="xsd:string"/>
        <xsd:element name="history" type="xsd:string"/>
        <xsd:element name="contact" type="contactsType"/>
        <xsd:element name="loc" type="locationType"/>
    </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="personInfoType">
    <xsd:sequence>
        <xsd:element name="type" type="xsd:normalizedString"/>
        <xsd:element name="birthdate" type="dateType"/>
        <xsd:element name="nationality" type="xsd:normalizedString"/>
        <xsd:element name="biography" type="xsd:string"/>
    </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="fulladdrType">
    <xsd:sequence>
        <xsd:element name="address" type="xsd:string"/>
        <xsd:element name="city" type="xsd:normalizedString"/>
        <xsd:element name="state" type="xsd:normalizedString"/>
        <xsd:element name="country" type="xsd:normalizedString"/>
        <xsd:element name="zip" type="xsd:normalizedString"/>
    </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="contactsType">
    <xsd:sequence>
        <xsd:element name="phone" type="xsd:normalizedString"/>
        <xsd:element name="email" type="xsd:normalizedString"/>
        <xsd:element name="mail" type="fulladdrType"/>
    </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="impactType">
    <xsd:sequence>
        <xsd:element name="human" type="humanImpType"/>
        <xsd:element name="economic" type="econImpType"/>
    </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="humanImpType">
    <xsd:sequence>
        <xsd:element name="deaths" type="xsd:integer"/>
        <xsd:element name="displaced" type="xsd:integer"/>
        <xsd:element name="injured" type="xsd:integer"/>
        <xsd:element name="missing" type="xsd:integer"/>
        <xsd:element name="misc" type="xsd:string"/>
    </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="econImpType">
    <xsd:sequence>
        <xsd:element name="amount" type="xsd:integer"/>
        <xsd:element name="currency" type="xsd:normalizedString"/>
        <xsd:element name="misc" type="xsd:string"/>
    </xsd:sequence>
</xsd:complexType>
   
<xsd:complexType name="extType">
    <xsd:sequence>
        <xsd:element name="site" type="xsd:normalizedString"/>
        <xsd:element name="title" type="xsd:normalizedString"/>
        <xsd:element name="url" type="xsd:token"/>
        <xsd:element name="description" type="xsd:string" minOccurs="0" maxOccurs="1" />
    </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="extLinkType">
    <xsd:sequence>
        <xsd:element name="primaryImage" type="extType" />
        <xsd:element name="image" type="extType" minOccurs="1" maxOccurs="unbounded"/>
        <xsd:element name="video" type="extType" minOccurs="1" maxOccurs="unbounded"/>
        <xsd:element name="social" type="extType" minOccurs="1" maxOccurs="unbounded"/>
        <xsd:element name="ext" type="extType" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="referenceType">
    <xsd:attribute name="idref" type="xsd:IDREF" use="required"/>
</xsd:complexType>

</xsd:schema>

=== bdharris08/cs373-wc/groupsxmls/cperez_wc3.xml
<worldCrises xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="WC2.xsd">

<!-- ......CRISIS...... -->

<!--..................................... Rwanda Genocide .....................................-->

  <crisis id = "RwandaGen">

    <name>Rwanda Genocide</name>

    <info>

      <history>There had always been heavy ethnic tension between the majority Hutu people and the Tutsis in Rwanda since the country's establishment. The Hutu both resented and feared the Tutsi minority for the decades of oppression they had to withstand. They finally overthew the Tutsi monarchy in a rebellion in 1959-1962 and established their own Hutu lead government. In the years following, social, economic, and political pressures grew and the Hutu political elite blamed the entire Tutsi minority for these problems. Soon after, a Tutsi-dominated rebel group, the Rwandan Patriotic Front, made a push to overthrow the Hutu led government; this led to a civil war and heavier resentment of the Tutsi people. The civil war ended in 1994 where President Juvenal Habyarimana signed a cease-fire with the Tutsi rebel group.  

In April 1994, shortly after President Habyarimana's plane was shot down violence errupted overnight in cities and towns around the country. The Hutu extremist political party had organized two primary militia groups to carry out the genocide of the Tutsis in advance in order to maintain their political power/influence. These two groups carried out mass murders on Tutsi men, women, and children, as well as Hutu people who were against the murders. Though the two militia groups were responsible for initiating many of the attacks on the Tutsi people, the actual murders were carried out by Hutu civilians; they were given the order by militia groups to either kill their Tutsi friends/neighbors or be killed themselves. Many Hutu civilians had no trouble killing them since there was much resent towards them over the past years. This genocide continued for three months until the Rwandan Patriotic Front (RPF), a rebel group composed of mostly Tutsi refugees, defeated the Hutu perpetrator regime and its supporters.</history>
      <help>Awareness</help>
      <resources></resources>
      <type>Murder</type>

      <time>
        <time></time>
        <day>06</day>
        <month>04</month>
        <year>1994</year>
        <misc></misc>
      </time>

      <loc>
        <city></city>
        <region></region>
        <country>Rwanda</country>
      </loc>

      <impact>

        <human>
          <deaths>1000000</deaths>
          <displaced>0</displaced>
          <injured>80000</injured>
          <missing>10000</missing>
          <misc></misc>
        </human>

        <economic>
          <amount>1000000</amount>
          <currency></currency>
          <misc></misc>
        </economic>

      </impact>

    </info>

    <ref>

      <primaryImage>
        <site/>
        <title>Rwanda Genocide Image</title>
        <url>http://saharareporters.com/sites/default/files/page_images/articles/2012/Genocide%20Rwanda.jpg?1334587404</url>
        <description>Mass grave for the lost during the genocide.</description>
      </primaryImage>

      <image>
        <site>Wikipedia</site>
        <title>Ntrama Church Altar</title>
        <url>http://upload.wikimedia.org/wikipedia/commons/2/24/Ntrama_Church_Altar.jpg</url>
        <description>Church where hundreds of people were barricaded inside and killed.</description>
      </image>

      <video>
        <site>YouTube</site>
        <title>Ghosts of Rwanda</title>
        <url>http://www.youtube.com/embed/xON22c7pZ6c</url>
        <description>Documentary of the Rwanda genocide.</description>
      </video>

      <social>
        <site></site>
        <title></title>
        <url></url>
        <description></description>
      </social>

      <ext>
        <site></site>
        <title></title>
        <url></url>
        <description></description>
      </ext>

    </ref>

    <misc>The Rwandan Genocide was the 1994 mass murder of an estimated 800,000 people in the small East African nation of Rwanda.</misc>

    <org idref = "OutreachProg"/>
    <person idref = "PaulRuse"/>

  </crisis>

<!--..................................... 2010 Chilean Earthquake .....................................-->

  <crisis id = "ChileanEarth">

    <name>2010 Chilean Earthquake</name>

    <info>

      <history>Chile's Pacific coast lies on the "Ring of Fire", the line frequent earthquakes and volcanic eruptions that circles the Pacific rim.  There has been 123 documented notable earthquakes with its epicenter within Chile since 1570.  The largest magintude earthquake occurred May 22, 1960 with a magnitude of 9.5, which is to date the most powerful earthquake ever recorded on earth.  The most recent earthquake occurred March 25, 2012 with a magnitude of 7.1.  This history of frequent earthquakes has made Chile one of the most well-prepared nations against earthquakes.  Chile has strict building codes, robust emergency response, and an educated population. Homes and buildings in Chile are built to ride out earthquakes, their steel skeletons designed to sway with seismic waves.  Also Chile has the most world-renowned seismologists and earthquake engineers per capita. These professionals are heeded by the government to advise in government contingency planning.  Finally, the people in Chile have most likely experienced an earthquake before and know how to react when one occurs (by sheltering under tables and door frames).

An earthquake of 8.8 magnitude occured off the coast of central Chile, lasting for about three minutes.  The earthquake ranks as the sixth largest earthquake recorded and was felt throughout most of Chile and many other South American countries.  It also triggered a tsunami which devastated the south-central Chilean coast and damaged areas in California and Japan. The earthquake generated a blackout that affected 93% of the country, lasting several days.  Chile was declared to be in a "state of catastrophe" by President Michelle Bachelet, who deployed military troops to take control of the most affected areas.  525 people lost their lives and 9% of the population lost their homes.  The total loss to Chilean economy is estimated to be at US$15-30 billion.</history>
      <help>Donations, Medical Supplies, Volunteers</help>
      <resources></resources>
      <type>Natural Disaster</type>

      <time>
        <time></time>
        <day>27</day>
        <month>02</month>
        <year>2010</year>
        <misc></misc>
      </time>

      <loc>
        <city></city>
        <region></region>
        <country>Chile</country>
      </loc>

      <impact>

        <human>
          <deaths>525</deaths>
          <displaced>0</displaced>
          <injured>0</injured>
          <missing>25</missing>
          <misc></misc>
        </human>

        <economic>
          <amount>22500000000</amount>
          <currency></currency>
          <misc></misc>
        </economic>

      </impact>

    </info>

    <ref>

      <primaryImage>
        <site>listofworld.com</site>
        <title>Chilean Road After Earthquake</title>
        <url>http://www.listsofworld.com/wp-content/uploads/2011/12/Largest-earthquake-2010-Chile-Earthquake.jpg</url>
        <description></description>
      </primaryImage>

      <image>
        <site></site>
        <title>Affected Area</title>
        <url>http://upload.wikimedia.org/wikipedia/commons/8/8e/2010_Chile_earthquake_epicenter.png</url>
        <description>Image of where the earthquake took place and the surrounding areas that were near it.</description>
      </image>

      <image>
        <site></site>
        <title>Specific Areas Affected</title>
        <url>http://upload.wikimedia.org/wikipedia/commons/6/68/2010_Maule_earthquake_intensity_USGS.jpg</url>
        <description>Specifies the regions in the country of Chile and the intensity that each one got hit with.</description>
      </image>

      <image>
        <site></site>
        <title>Torre O'Higgins After Quake</title>
        <url>http://upload.wikimedia.org/wikipedia/commons/9/9b/Torre_O%C2%B4Higgins_conce.jpg</url>
        <description>O'Higgins Tower after the quake</description>
      </image>

      <video>
        <site>YouTube</site>
        <title>The 2010 Great Chile Earthquake and its Aftershocks</title>
        <url>http://www.youtube.com/embed/kr44Q_b_CX4</url>
        <description>Animation that shows the seismic history of the Earthquake that hit Chile and its aftershocks that continued from January 1 to March 11.</description>
      </video>

      <social>
        <site>Facebook</site>
        <title>Chile Earthquake</title>
        <url>https://www.facebook.com/chileearthquakeupdate?filter=3</url>
        <description>Coverage of the events of the Chilean Earthquake as they unfolded.</description>
      </social>

      <ext>
        <site></site>
        <title>US Department of State</title>
        <url>http://www.state.gov/p/wha/ci/ci/earthquake/index.htm</url>
        <description></description>
      </ext>

      <ext>
        <site></site>
        <title>Multidisciplinary Center for Earthquake Engineering Research</title>
        <url>http://mceer.buffalo.edu/infoservice/disasters/Chile-Earthquake-2010.asp</url>
        <description></description>
      </ext>

    </ref>

    <misc>The 2010 Chile earthquake occurred off the coast of central Chile on February 27th 2010 with a magnitude of 8.8 on the moment magnitude scale and lasted for about three minutes</misc>

    <org idref = "SalvationArmy"/>
    <person idref = "MichelleBach"/>

  </crisis>

<!--.....................................  .....................................-->

  <crisis id = "AvianFlu">

    <name>Avian Flu</name>

    <info>
